# Generated by Django 4.1.6 on 2023-03-06 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_venue_phone_venue_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='votes',
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.poll')),
                ('user_votes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.venue')),
            ],
        ),
    ]
