# Generated by Django 4.1.6 on 2023-03-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_poll_total_votes_remove_venue_poll_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
    ]
