# Generated by Django 4.1.6 on 2023-03-06 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_votes_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='venues',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.venue'),
        ),
    ]
