# Generated by Django 4.1.6 on 2023-03-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_poll_venues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='venues',
        ),
        migrations.AddField(
            model_name='poll',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='venues', to='base.venue'),
        ),
    ]
