# Generated by Django 4.1.6 on 2023-03-06 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_option_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
