# Generated by Django 4.1.6 on 2023-03-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_option_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='area',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
