# Generated by Django 4.1.6 on 2023-03-11 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_poll_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='user_votes',
        ),
        migrations.AddField(
            model_name='option',
            name='user_votes',
            field=models.ManyToManyField(blank=True, related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
